# Generated by Django 6.0.2 on 2026-03-03 20:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cidade'], name='core_destin_cidade_bb8ab5_idx'), models.Index(fields=['estado'], name='core_destin_estado_fd2060_idx')],
                'unique_together': {('cidade', 'estado', 'pais')},
            },
        ),
        migrations.CreateModel(
            name='Hospedagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospedagens', to='core.destino')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='planejada', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens_criadas', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='core.destino')),
                ('hospedagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='core.hospedagem')),
                ('transporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens', to='core.transporte')),
            ],
        ),
        migrations.CreateModel(
            name='Viajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('data_nascimento', models.DateField()),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contato_emergencia_nome', models.CharField(blank=True, max_length=200)),
                ('contato_emergencia_telefone', models.CharField(blank=True, max_length=20)),
                ('observacoes_medicas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nome_completo'], name='core_viajan_nome_co_b2d424_idx'), models.Index(fields=['cpf'], name='core_viajan_cpf_2ea5d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ViagemViajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('pago', 'Pago')], default='pendente', max_length=20)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viagem')),
                ('viajante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.viajante')),
            ],
        ),
        migrations.AddField(
            model_name='viagem',
            name='viajantes',
            field=models.ManyToManyField(related_name='viagens', through='core.ViagemViajante', to='core.viajante'),
        ),
        migrations.AddIndex(
            model_name='hospedagem',
            index=models.Index(fields=['nome'], name='core_hosped_nome_593292_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='viagemviajante',
            unique_together={('viagem', 'viajante')},
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['data_inicio'], name='core_viagem_data_in_4b327b_idx'),
        ),
        migrations.AddIndex(
            model_name='viagem',
            index=models.Index(fields=['status'], name='core_viagem_status_07b765_idx'),
        ),
    ]
