# Generated by Django 6.0.2 on 2026-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='vagas_disponiveis',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
